config/routes.rb
Pepen::Application.routes.draw do
 
  resources :usuario_sucursal_catalogo, only: [:index, :show]
  resources :catalogo_pdf_vendedor
  
  post 'movimiento/:catalogo_id' => 'usuario_sucursal_catalogo#movimiento', as: :movimiento
  resources :inventarios

  resources :sucursals

  resources :costos

  resources :gastos
    
devise_for :users
devise_scope :user do
  authenticated :user do
    root :to => 'menu#index', as: :authenticated_root
  end
  unauthenticated :user do
root :to => 'devise/sessions#new', as: :unauthenticated_root
  end
end
  
  resources :users
  
  resources :catalogos
  get "menu/index"
  resources :categoria

 get "resume/index"

  

end

app/models/catalogo.rb
class Catalogo < ActiveRecord::Base
  has_many :inventarios, dependent: :destroy  
  belongs_to :categoria, class_name: 'Categorium'

  mount_uploader :avatar, AvatarUploader
  
  def to_s
    self.nombre_producto
  end
end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
  has_many :catalogos,  dependent: :destroy,  foreign_key: "categoria_id"
  
  def to_s
    self.nombre
  end
end

app/models/costo.rb
class Costo < ActiveRecord::Base
end

app/models/devolucion.rb
class Devolucion < ActiveRecord::Base
  belongs_to :user
  belongs_to :catalogo
  belongs_to :sucursal
end

app/models/gasto.rb
class Gasto < ActiveRecord::Base
end

app/models/inventario.rb
class Inventario < ActiveRecord::Base

  belongs_to :catalogo
  belongs_to :sucursal

end

app/models/sucursal.rb
class Sucursal < ActiveRecord::Base
  
  has_many :inventarios, dependent: :destroy
  belongs_to :user
  validates :user_id, uniqueness: true
  scope :almacen, -> { where(almacen: true) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,# :registerable, (quito que searegistrable)
         :recoverable, :rememberable, :trackable, :validatable
  
   validates :role, presence: true
  
  has_one :sucursal, dependent: :destroy
  
  enum role: [:admin, :user]

  def to_s
    self.email
  end
end

app/models/ventum.rb
class Ventum < ActiveRecord::Base
  belongs_to :user
  belongs_to :catalogo
  belongs_to :sucursal
end

app/controllers/catalogos_controller.rb
class CatalogosController < ApplicationController
  before_action :set_catalogo, only: [:show, :edit, :update, :destroy]
  before_action :validate_does_admin
  def index   
    @catalogos = Catalogo.all.order(nombre_producto: :asc)
    respond_to do |format|
      format.html 
      format.pdf { render_catalogo_list(@catalogos)}
    end
  end
        
  def show
    #respond_with(@catalogo)
  end

  def new
    @catalogo = Catalogo.new
  end

  def edit
  
  end

  def create
    @catalogo = Catalogo.new(catalogo_params)
      respond_to do |format|
      if @catalogo.save  
        format.html {redirect_to @catalogo} 
      else 
        format.html {render :new}
      end
    end
  end

  def update
    respond_to do |format|
      if @catalogo.update(catalogo_params)  
        format.html {redirect_to @catalogo} 
      else 
        format.html {render :edit}
      end
    end
  end

  def destroy
    @catalogo.destroy
    redirect_to (catalogos_path)
  end

  private
  def set_catalogo
    @catalogo = Catalogo.find(params[:id])
  end

  def catalogo_params
    params.require(:catalogo).permit(:categoria_id, :nombre_producto, :marca, :descripcion, :medidas, :precio_vendedor, :precio_publico, :costo_produccion, :avatar)
  end
  
  
  def render_catalogo_list(catalogo)
    report = ThinReports::Report.new layout: File.join(Rails.root, 'app', 'reports', 'report.tlf')

    catalogo.each do |c|
      report.list.add_row do |row|
        row.values clave: c.id, 
          categoria: c.categoria, 
          producto: c.nombre_producto, 
          descripcion: c.descripcion, 
          marca: c.marca,
          medidas: c.medidas,
          precio_vendedor: c.precio_vendedor,
          precio_publico: c.precio_publico
#          row.item(:imagen).value('public/uploads/catalogo/avatar/16/Screenshot_from_2015-09-29_18-19-10.png')
         row.item(:imagen).value(c.avatar.path) unless c.avatar.to_s.blank?
      end
    end

      
    send_data report.generate, filename: 'catalogo_pepen.pdf', 
      type: 'application/pdf', 
      disposition: 'attachment'
  end

end

app/controllers/costos_controller.rb
class CostosController < ApplicationController
  before_action :set_costo, only: [:show, :edit, :update, :destroy]
  before_action :validate_does_admin
  
  respond_to :html

  def index
    @costos = Costo.all
    respond_with(@costos)
  end

  def show
    respond_with(@costo)
  end

  def new
    @costo = Costo.new
    respond_with(@costo)
  end

  def edit
  end

  def create
    @costo = Costo.new(costo_params)
    @costo.save
    respond_with(@costo)
  end

  def update
    @costo.update(costo_params)
    respond_with(@costo)
  end

  def destroy
    @costo.destroy
    respond_with(@costo)
  end

  private
    def set_costo
      @costo = Costo.find(params[:id])
    end

    def costo_params
      params.require(:costo).permit(:concepto, :descripcion, :monto, :no_factura, :fecha)
    end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
 before_action :validate_does_admin
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: [:show, :edit, :update, :destroy]
before_action :validate_does_admin
  # GET /users
  # GET /users.json
  def index
    @users = User.all.order(email: :asc)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params.delete_if{|k,v| v.blank?})
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :role, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catalogos_helper.rb
module CatalogosHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/costos_helper.rb
module CostosHelper
end

app/helpers/gastos_helper.rb
module GastosHelper
end

app/helpers/inventarios_helper.rb
module InventariosHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/helpers/sucursals_helper.rb
module SucursalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/catalogos/_form.html.erb
<%= form_for(@catalogo) do |f| %>
  <% if @catalogo.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@catalogo.errors.count, "error") %> prohibited this catalogo from being saved:</h2>
        <ul>
            <% @catalogo.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
  <% end %>

  <div class="field">
      <%= f.label :categoria_id %><br>
  <%#= f.text_field :categoria_id %>
      <%= f.select :categoria_id, Categorium.all.collect{|c| [c.nombre, c.id]} %><br>
      <%= link_to 'Administrar categorias', categoria_path %>
  </div>
  <div class="field">
      <%= f.label :nombre_producto %><br>
      <%= f.text_field :nombre_producto %>
  </div>
  <div class="field">
      <%= f.label :marca %><br>
      <%= f.text_field :marca %>
  </div>
  <div class="field">
      <%= f.label :descripcion %><br>
      <%= f.text_area :descripcion %>
  </div>
  <div class="field">
      <%= f.label :medidas %><br>
      <%= f.text_field :medidas %>
  </div>
  <div class="field">
      <%= f.label :precio_vendedor %><br>
      <%= f.text_field :precio_vendedor %>
  </div>
  <div class="field">
      <%= f.label :precio_publico %><br>
      <%= f.text_field :precio_publico %>
  </div>
  <div class="field">
      <%= f.label :costo_produccion %><br>
      <%= f.text_field :costo_produccion %>
  </div>
  <div>
      <%= f.file_field :avatar %>
  </div>
  <div class="actions">
      <%= f.submit %>
  </div>
<% end %>

app/views/catalogos/edit.html.erb
<h1>Editing catalogo</h1>

<%= render 'form' %>

<%= link_to 'Show', @catalogo %> |
<%= link_to 'Back', catalogos_path %>

app/views/catalogos/index.html.erb
<h1>Catalogo de productos</h1>


<br><%= link_to 'Agregar a catalogo', new_catalogo_path, :class=>"btn btn-default btn-block" %>

<br> <br>
<table class="table table-hover table-bordered" border="2"  width="400">
  <thead>
    <tr>      
      <th>Id Producto</th>
      <th>Categoria</th>
      <th>Nombre producto</th>
      <th>Marca</th>
      <th>Descripcion</th>
      <th>Medidas</th>
      <th>Precio vendedor</th>
      <th>Precio publico</th>
      <th>Costo produccion</th>
      <th>Imagen</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @catalogos.each do |catalogo| %>
      <tr> 
        <td><%= catalogo.id %></td>
        <td><%= link_to catalogo.categoria, catalogo.categoria %></td>
        <td><%= catalogo.nombre_producto %></td>
        <td><%= catalogo.marca %></td>
        <td><%= catalogo.descripcion %></td>
        <td><%= catalogo.medidas %></td>
        <td><%= catalogo.precio_vendedor %></td>
        <td><%= catalogo.precio_publico %></td>
        <td><%= catalogo.costo_produccion %></td>
        <td><%= image_tag catalogo.avatar_url(:thumb).to_s %></td>
        <td><%= link_to 'Show', catalogo, :class=>"btn-info btn-sm" %></td>
        <td><%= link_to 'Edit', edit_catalogo_path(catalogo),:class=>"btn-warning btn-sm" %></td>
        <td><%= link_to 'Destroy', catalogo, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/catalogos/new.html.erb
<h1>New catalogo</h1>

<%= render 'form' %>

<%= link_to 'Back', catalogos_path %>

app/views/catalogos/show.html.erb
<p id="notice"><%= notice %></p>


<table class="table-bordered">
    <tr>
        <td align="center">

            <p> <strong>Imagen</strong></p>
            <p>            
                <%= image_tag @catalogo.avatar_url(:show).to_s %>
            </p>
        </td>   
        <td>
            <p></p>
            <p>
                <strong>Categoria:</strong>
                <%= @catalogo.categoria_id %>
            </p>

            <p>
                <strong>Nombre producto:</strong>
                <%= @catalogo.nombre_producto %>
            </p>
            <p>
                <strong>Marca:</strong>
                <%= @catalogo.marca %>
            </p>

            <p>
                <strong>Descripcion:</strong>
                <%= @catalogo.descripcion %>
            </p>

            <p>
                <strong>Medidas:</strong>
                <%= @catalogo.medidas %>
            </p>

            <p>
                <strong>Precio vendedor:</strong>
                <%= @catalogo.precio_vendedor %>
            </p>

            <p>
                <strong>Precio publico:</strong>
                <%= @catalogo.precio_publico %>
            </p>

            <p>
                <strong>Costo produccion:</strong>
                <%= @catalogo.costo_produccion %>
            </p>

        </td>
    </tr>

</table>





<%= link_to 'Edit', edit_catalogo_path(@catalogo) %> |
<%= link_to 'Back', catalogos_path %>