config/routes.rb
Pepen::Application.routes.draw do
 
  resources :usuario_sucursal_catalogo, only: [:index, :show]
  resources :catalogo_pdf_vendedor
  
  post 'movimiento/:catalogo_id' => 'usuario_sucursal_catalogo#movimiento', as: :movimiento
  resources :inventarios

  resources :sucursals

  resources :costos

  resources :gastos
    
devise_for :users
devise_scope :user do
  authenticated :user do
    root :to => 'menu#index', as: :authenticated_root
  end
  unauthenticated :user do
root :to => 'devise/sessions#new', as: :unauthenticated_root
  end
end
  
  resources :users
  
  resources :catalogos
  get "menu/index"
  resources :categoria

 get "resume/index"

  

end

app/models/catalogo.rb
class Catalogo < ActiveRecord::Base
  has_many :inventarios, dependent: :destroy  
  belongs_to :categoria, class_name: 'Categorium'

  mount_uploader :avatar, AvatarUploader
  
  def to_s
    self.nombre_producto
  end
end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
  has_many :catalogos,  dependent: :destroy,  foreign_key: "categoria_id"
  
  def to_s
    self.nombre
  end
end

app/models/costo.rb
class Costo < ActiveRecord::Base
end

app/models/devolucion.rb
class Devolucion < ActiveRecord::Base
  belongs_to :user
  belongs_to :catalogo
  belongs_to :sucursal
end

app/models/gasto.rb
class Gasto < ActiveRecord::Base
end

app/models/inventario.rb
class Inventario < ActiveRecord::Base

  belongs_to :catalogo
  belongs_to :sucursal

end

app/models/sucursal.rb
class Sucursal < ActiveRecord::Base
  
  has_many :inventarios, dependent: :destroy
  belongs_to :user
  validates :user_id, uniqueness: true
  scope :almacen, -> { where(almacen: true) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,# :registerable, (quito que searegistrable)
         :recoverable, :rememberable, :trackable, :validatable
  
   validates :role, presence: true
  
  has_one :sucursal, dependent: :destroy
  
  enum role: [:admin, :user]

  def to_s
    self.email
  end
end

app/models/ventum.rb
class Ventum < ActiveRecord::Base
  belongs_to :user
  belongs_to :catalogo
  belongs_to :sucursal
end

app/controllers/costos_controller.rb
class CostosController < ApplicationController
  before_action :set_costo, only: [:show, :edit, :update, :destroy]
  before_action :validate_does_admin
  
  respond_to :html

  def index
    @costos = Costo.all
    respond_with(@costos)
  end

  def show
    respond_with(@costo)
  end

  def new
    @costo = Costo.new
    respond_with(@costo)
  end

  def edit
  end

  def create
    @costo = Costo.new(costo_params)
    @costo.save
    respond_with(@costo)
  end

  def update
    @costo.update(costo_params)
    respond_with(@costo)
  end

  def destroy
    @costo.destroy
    respond_with(@costo)
  end

  private
    def set_costo
      @costo = Costo.find(params[:id])
    end

    def costo_params
      params.require(:costo).permit(:concepto, :descripcion, :monto, :no_factura, :fecha)
    end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
 before_action :validate_does_admin
  def index
  end
end

app/controllers/sucursals_controller.rb
class SucursalsController < ApplicationController
  before_action :validate_does_admin
  before_action :set_sucursal, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @sucursals = Sucursal.all.order(nombre_sucursal: :asc)
    respond_with(@sucursals)
  end

  def show
    respond_with(@sucursal)
  end

  def new
    @sucursal = Sucursal.new
    respond_with(@sucursal)
  end

  def edit
  end

  def create
    @sucursal = Sucursal.new(sucursal_params)
    @sucursal.save
    respond_with(@sucursal)
  end

  def update
    @sucursal.update(sucursal_params)
    respond_with(@sucursal)
  end

  def destroy
    @sucursal.destroy
    respond_with(@sucursal)
  end

  private
    def set_sucursal
      @sucursal = Sucursal.find(params[:id])
    end

    def sucursal_params
      params.require(:sucursal).permit(:nombre_sucursal, :user_id, :telefono, :direccion, :ciudad ,:pais, :almacen)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: [:show, :edit, :update, :destroy]
before_action :validate_does_admin
  # GET /users
  # GET /users.json
  def index
    @users = User.all.order(email: :asc)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params.delete_if{|k,v| v.blank?})
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :role, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catalogos_helper.rb
module CatalogosHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/costos_helper.rb
module CostosHelper
end

app/helpers/gastos_helper.rb
module GastosHelper
end

app/helpers/inventarios_helper.rb
module InventariosHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/helpers/sucursals_helper.rb
module SucursalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/sucursals/_form.html.erb
<%= form_for(@sucursal) do |f| %>
  <% if @sucursal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sucursal.errors.count, "error") %> prohibited this sucursal from being saved:</h2>

      <ul>
      <% @sucursal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre_sucursal %><br>
    <%= f.text_field :nombre_sucursal %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.select :user_id, User.all.collect{|c| [c.email, c.id]} %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.number_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_area :direccion %>
  </div>

<div class="field">
    <%= f.label :ciudad %><br>
    <%= f.text_field :ciudad %>
  </div>

  <div class="field">
    <%= f.label :pais %><br>
    <%= f.text_field :pais %>
  </div>
  <div class="field">
    <%= f.label :almacen %><br>
    <%= f.select :almacen, [['Sì', true], ['No', false]] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sucursals/edit.html.erb
<h1>Editing sucursal</h1>

<%= render 'form' %>

<%= link_to 'Show', @sucursal %> |
<%= link_to 'Back', sucursals_path %>

app/views/sucursals/index.html.erb
<h1>Listado de sucursales</h1>

<table class="table table-hover table-bordered" border="2"  width="400">
  <thead>
    <tr>
        
      <th>Id Sucursal</th>
      <th>Nombre sucursal</th>
      <th>Responsable</th>
      <th>Telefono</th>
      <th>Direccion</th>
      <th>Ciudad</th>
      <th>Pais</th>
      <th></th>
      <th></th>
      
      
    </tr>
  </thead>

  <tbody>
    <% @sucursals.each do |sucursal| %>
      <tr>
        <td><%= sucursal.id %></td>
        <td><%= sucursal.nombre_sucursal %></td>
        <td><%= sucursal.user %></td>
        <td><%= sucursal.telefono %></td>
        <td><%= sucursal.direccion %></td>
        <td><%= sucursal.ciudad %></td>
        <td><%= sucursal.pais %></td>
      
        <td><%= link_to 'Show', sucursal, :class=>"btn-info btn-sm" %></td>
        <td><%= link_to 'Edit', edit_sucursal_path(sucursal),:class=>"btn-warning btn-sm"  %></td>
        <td><%= link_to 'Destroy', sucursal, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn-danger btn-sm"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sucursal', new_sucursal_path,  :class=>"btn btn-success" %>

app/views/sucursals/new.html.erb
<h1>New sucursal</h1>

<%= render 'form' %>

<%= link_to 'Back', sucursals_path %>

app/views/sucursals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre sucursal:</strong>
  <%= @sucursal.nombre_sucursal %>
</p>

<p>
  <strong>Responsable:</strong>
  <%#= @sucursal.user.id %>
  <%= link_to @sucursal.user, @sucursal.user %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @sucursal.telefono %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @sucursal.direccion %>
</p>

<p>
  <strong>Ciudad:</strong>
  <%= @sucursal.ciudad %>
</p>

<p>
  <strong>Pais:</strong>
  <%= @sucursal.pais %>
</p>
<p>
  <strong>Almacen:</strong>
  <%= @sucursal.almacen ? 'Si' : 'No'%>
</p>

<%= link_to 'Edit', edit_sucursal_path(@sucursal) %> |
<%= link_to 'Back', sucursals_path %>