config/routes.rb
Pepen::Application.routes.draw do
 
  resources :usuario_sucursal_catalogo, only: [:index, :show]
  resources :catalogo_pdf_vendedor
  
  post 'movimiento/:catalogo_id' => 'usuario_sucursal_catalogo#movimiento', as: :movimiento
  resources :inventarios

  resources :sucursals

  resources :costos

  resources :gastos
    
devise_for :users
devise_scope :user do
  authenticated :user do
    root :to => 'menu#index', as: :authenticated_root
  end
  unauthenticated :user do
root :to => 'devise/sessions#new', as: :unauthenticated_root
  end
end
  
  resources :users
  
  resources :catalogos
  get "menu/index"
  resources :categoria

 get "resume/index"

  

end

app/models/catalogo.rb
class Catalogo < ActiveRecord::Base
  has_many :inventarios, dependent: :destroy  
  belongs_to :categoria, class_name: 'Categorium'

  mount_uploader :avatar, AvatarUploader
  
  def to_s
    self.nombre_producto
  end
end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
  has_many :catalogos,  dependent: :destroy,  foreign_key: "categoria_id"
  
  def to_s
    self.nombre
  end
end

app/models/costo.rb
class Costo < ActiveRecord::Base
end

app/models/devolucion.rb
class Devolucion < ActiveRecord::Base
  belongs_to :user
  belongs_to :catalogo
  belongs_to :sucursal
end

app/models/gasto.rb
class Gasto < ActiveRecord::Base
end

app/models/inventario.rb
class Inventario < ActiveRecord::Base

  belongs_to :catalogo
  belongs_to :sucursal

end

app/models/sucursal.rb
class Sucursal < ActiveRecord::Base
  
  has_many :inventarios, dependent: :destroy
  belongs_to :user
  validates :user_id, uniqueness: true
  scope :almacen, -> { where(almacen: true) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,# :registerable, (quito que searegistrable)
         :recoverable, :rememberable, :trackable, :validatable
  
   validates :role, presence: true
  
  has_one :sucursal, dependent: :destroy
  
  enum role: [:admin, :user]

  def to_s
    self.email
  end
end

app/models/ventum.rb
class Ventum < ActiveRecord::Base
  belongs_to :user
  belongs_to :catalogo
  belongs_to :sucursal
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
 before_action :validate_does_admin
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catalogos_helper.rb
module CatalogosHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/costos_helper.rb
module CostosHelper
end

app/helpers/gastos_helper.rb
module GastosHelper
end

app/helpers/inventarios_helper.rb
module InventariosHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/helpers/sucursals_helper.rb
module SucursalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>PAPEN Bienvenido</title>

    <%= favicon_link_tag 'favico.jpg' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>

<body>

    <center>
        <br><br>
        <table class="table-responsive" width="1024">
            <tr bgcolor="white" align="center">
                <td>
                    <p class="navbar-text pull-right">
                        <% if user_signed_in? %>
                        Logged in as <strong><%= current_user.email %></strong>.
                        <%#= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
                        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                        <% else %>
                        <%#= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
                        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
                        <% end %>
                </td>
            </tr>
            <tr bgcolor="white" align="center">
                <td>
                    <%= image_tag("prueba1.jpg")%>
                </td>
            </tr>
            <tr bgcolor="white">
                <td>
                    <% if user_signed_in? %>
                    <nav class="navbar navbar-inverse">
                        <ul class="nav navbar-nav">
                            <% if current_user.user? %>
                            <li><%= link_to "Existencias vendedor", usuario_sucursal_catalogo_index_path %></li>
                            <li><%=  link_to 'Descargar Catalogo', catalogo_pdf_vendedor_index_path(format: 'pdf') %></li>
                            <% else 
                                end  
                              if current_user.admin? %>
                            <li><%= link_to "Inicio", menu_index_path %> </li>
                            <li>
                                <a href="#" data-toggle="dropdown">Descargas<span class="caret"></span></button>
                                    <ul class="dropdown-menu">
                                        <li><%=  link_to 'Catalogo cliente', catalogo_pdf_vendedor_index_path(format: 'pdf') %></li>
                                        <li><%=  link_to 'Catalogo vendedor', catalogos_path(format: 'pdf')%></li>
                                    </ul>
                            </li>
                            <li><%= link_to "Administración de Catalogo", catalogos_path %> </li>
                            <li><%= link_to "Inventario", inventarios_path%></li>
                            <li><%= link_to "Gastos", gastos_path %></li>
                            <li><%= link_to "Costos", costos_path %></li>
                            <li><%= link_to "Sucursales", sucursals_path%></li>
                            <li><%= link_to "Usuarios", users_path%></li>
                            <li>
                                <a href="#" data-toggle="dropdown">Resumen de operaciones<span class="caret"></span></button>
                                    <ul class="dropdown-menu">
                                        <li><%= link_to "Resumen de operaciones CSV", resume_index_path(format: 'csv')%></li>
                                        <li><%= link_to "Resumen de operaciones PDF", resume_index_path(format: 'pdf')%></li>
                                    </ul>
                            </li>


                            <%else%>
                            <% end %>
                        </ul>
                    </nav>
                    <% else %>
                    <%#*not show nav-bar%>
                    <% end %>
                    <%if notice%>
                    <p class="notice"><%= notice %></p>
                    <%end%>
                    <%if alert%>
                    <p class="alert"><%= alert %></p>
                    <%end%>
                </td>
            </tr>


            <tr bgcolor="white" align="center">

                <td> <%= yield %> <br><br></td>

            </tr>
            <tr bgcolor="white">
                <td bgcolor="black">

                    <div id="footer" align="center">
                        <font color="White" size="3">2015 pepen derechos reservados</font>
                    </div>

                </td>
            </tr>
        </table>
        <br>
    </center>
</body>

</html>