config/routes.rb
Pepen::Application.routes.draw do
 
  resources :usuario_sucursal_catalogo, only: [:index, :show]
  resources :catalogo_pdf_vendedor
  
  post 'movimiento/:catalogo_id' => 'usuario_sucursal_catalogo#movimiento', as: :movimiento
  resources :inventarios

  resources :sucursals

  resources :costos

  resources :gastos
    
devise_for :users
devise_scope :user do
  authenticated :user do
    root :to => 'menu#index', as: :authenticated_root
  end
  unauthenticated :user do
root :to => 'devise/sessions#new', as: :unauthenticated_root
  end
end
  
  resources :users
  
  resources :catalogos
  get "menu/index"
  resources :categoria

 get "resume/index"

  

end

app/models/catalogo.rb
class Catalogo < ActiveRecord::Base
  has_many :inventarios, dependent: :destroy  
  belongs_to :categoria, class_name: 'Categorium'

  mount_uploader :avatar, AvatarUploader
  
  def to_s
    self.nombre_producto
  end
end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
  has_many :catalogos,  dependent: :destroy,  foreign_key: "categoria_id"
  
  def to_s
    self.nombre
  end
end

app/models/costo.rb
class Costo < ActiveRecord::Base
end

app/models/devolucion.rb
class Devolucion < ActiveRecord::Base
  belongs_to :user
  belongs_to :catalogo
  belongs_to :sucursal
end

app/models/gasto.rb
class Gasto < ActiveRecord::Base
end

app/models/inventario.rb
class Inventario < ActiveRecord::Base

  belongs_to :catalogo
  belongs_to :sucursal

end

app/models/sucursal.rb
class Sucursal < ActiveRecord::Base
  
  has_many :inventarios, dependent: :destroy
  belongs_to :user
  validates :user_id, uniqueness: true
  scope :almacen, -> { where(almacen: true) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,# :registerable, (quito que searegistrable)
         :recoverable, :rememberable, :trackable, :validatable
  
   validates :role, presence: true
  
  has_one :sucursal, dependent: :destroy
  
  enum role: [:admin, :user]

  def to_s
    self.email
  end
end

app/models/ventum.rb
class Ventum < ActiveRecord::Base
  belongs_to :user
  belongs_to :catalogo
  belongs_to :sucursal
end

app/controllers/costos_controller.rb
class CostosController < ApplicationController
  before_action :set_costo, only: [:show, :edit, :update, :destroy]
  before_action :validate_does_admin
  
  respond_to :html

  def index
    @costos = Costo.all
    respond_with(@costos)
  end

  def show
    respond_with(@costo)
  end

  def new
    @costo = Costo.new
    respond_with(@costo)
  end

  def edit
  end

  def create
    @costo = Costo.new(costo_params)
    @costo.save
    respond_with(@costo)
  end

  def update
    @costo.update(costo_params)
    respond_with(@costo)
  end

  def destroy
    @costo.destroy
    respond_with(@costo)
  end

  private
    def set_costo
      @costo = Costo.find(params[:id])
    end

    def costo_params
      params.require(:costo).permit(:concepto, :descripcion, :monto, :no_factura, :fecha)
    end
end

app/controllers/gastos_controller.rb
class GastosController < ApplicationController
  before_action :set_gasto, only: [:show, :edit, :update, :destroy]
  before_action :validate_does_admin
  respond_to :html

  def index
    @gastos = Gasto.order(fecha: :desc)
    respond_with(@gastos)
  end

  def show
    respond_with(@gasto)
  end

  def new
    @gasto = Gasto.new
    respond_with(@gasto)
  end

  def edit
  end

  def create
    @gasto = Gasto.new(gasto_params)
    @gasto.save
    respond_with(@gasto)
  end

  def update
    @gasto.update(gasto_params)
    respond_with(@gasto)
  end

  def destroy
    @gasto.destroy
    respond_with(@gasto)
  end

  private
  def set_gasto
    @gasto = Gasto.find(params[:id])
  end

  def gasto_params
    params.require(:gasto).permit(:concepto, :descripcion, :monto, :no_factura, :fecha)
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
 before_action :validate_does_admin
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: [:show, :edit, :update, :destroy]
before_action :validate_does_admin
  # GET /users
  # GET /users.json
  def index
    @users = User.all.order(email: :asc)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params.delete_if{|k,v| v.blank?})
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :role, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catalogos_helper.rb
module CatalogosHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/costos_helper.rb
module CostosHelper
end

app/helpers/gastos_helper.rb
module GastosHelper
end

app/helpers/inventarios_helper.rb
module InventariosHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/helpers/sucursals_helper.rb
module SucursalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/costos/_form.html.erb
<%= form_for(@costo) do |f| %>
  <% if @costo.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@costo.errors.count, "error") %> prohibited this costo from being saved:</h2>

        <ul>
            <% @costo.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
  <% end %>

  <div class="field">
      <%= f.label :concepto %><br>
      <%= f.text_field :concepto %>
  </div>
  <div class="field">
      <%= f.label :descripcion %><br>
      <%= f.text_area :descripcion %>
  </div>
  <div class="field">
      <%= f.label :monto %><br>
      <%= f.text_field :monto %>
  </div>
  <div class="field">
      <%= f.label :no_factura %><br>
      <%= f.text_field :no_factura %>
  </div>
  <div class="field">
      <%= f.label :fecha %><br>
      <%= f.date_select:fecha%>
  </div>

  <div class="actions">
      <%= f.submit %>
  </div>
<% end %>

app/views/costos/edit.html.erb
<h1>Editing costo</h1>

<%= render 'form' %>

<%= link_to 'Show', @costo %> |
<%= link_to 'Back', costos_path %>

app/views/costos/index.html.erb
<h1>Listing costos</h1>

<table class="table table-hover table-bordered" border="2"  width="400">
  <thead>
    <tr>
        <th>Id Costo</th>
      <th>Concepto</th>
      <th>Descripcion</th>
      <th>Monto</th>
      <th>Factura No</th>
      <th>Fecha</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @costos.each do |costo| %>
      <tr>
          <td><%= costo.id %></td>
        <td><%= costo.concepto %></td>
        <td><%= costo.descripcion %></td>
        <td><%= costo.monto %></td>
        <td><%= costo.no_factura %></td>
        <td><%= costo.fecha %></td>
        <td><%= link_to 'Show', costo, :class=>"btn-info btn-sm" %></td>
        <td><%= link_to 'Edit', edit_costo_path(costo),:class=>"btn-warning btn-sm" %></td>
        <td><%= link_to 'Destroy', costo, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Costo', new_costo_path, :class=>"btn btn-success" %>

app/views/costos/new.html.erb
<h1>New costo</h1>

<%= render 'form' %>

<%= link_to 'Back', costos_path %>

app/views/costos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Concepto:</strong>
  <%= @costo.concepto %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @costo.descripcion %>
</p>

<p>
  <strong>Monto:</strong>
  <%= @costo.monto %>
</p>

<p>
  <strong>No Factura:</strong>
  <%= @costo.no_factura %>
</p>

<p>
  <strong>fecha:</strong>
  <%= @costo.fecha %>
</p>

<%= link_to 'Edit', edit_costo_path(@costo) %> |
<%= link_to 'Back', costos_path %>

app/views/gastos/_form.html.erb
<%= form_for(@gasto) do |f| %>
  <% if @gasto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gasto.errors.count, "error") %> prohibited this gasto from being saved:</h2>

      <ul>
      <% @gasto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :concepto %><br>
    <%= f.text_field :concepto %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :monto %><br>
    <%= f.text_field :monto %>
  </div>
<div class="field">
    <%= f.label :no_factura %><br>
    <%= f.text_field :no_factura %>
  </div>
<div class="field">
    <%= f.label :fecha %><br>
    <%= f.date_select:fecha%>
  </div>

<p></p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gastos/edit.html.erb
<h1>Editing gasto</h1>

<%= render 'form' %>

<%= link_to 'Show', @gasto %> |
<%= link_to 'Back', gastos_path %>

app/views/gastos/index.html.erb
<h1>Listing gastos</h1>

<table class="table table-hover table-bordered" border="2"  width="400">
  <thead>
    <tr>
      <th>Id Gasto</th>
      <th>Concepto</th>
      <th>Descripcion</th>
      <th>Monto</th>
      <th>No Factura</th>
      <th>Fecha</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @gastos.each do |gasto| %>
      <tr>
          <td><%= gasto.id %></td>
        <td><%= gasto.concepto %></td>
        <td><%= gasto.descripcion %></td>
        <td><%= gasto.monto %></td>
        <td><%= gasto.no_factura %></td>
        <td><%= gasto.fecha %></td>
        <td><%= link_to 'Show', gasto, :class=>"btn-info btn-sm" %></td>
        <td><%= link_to 'Edit', edit_gasto_path(gasto),:class=>"btn-warning btn-sm" %></td>
        <td><%= link_to 'Destroy', gasto, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gasto', new_gasto_path, :class=>"btn btn-success" %>

app/views/gastos/new.html.erb
<h1>New gasto</h1>

<%= render 'form' %>

<%= link_to 'Back', gastos_path %>

app/views/gastos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Concepto:</strong>
  <%= @gasto.concepto %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @gasto.descripcion %>
</p>

<p>
  <strong>Monto:</strong>
  <%= @gasto.monto %>
</p>
<p>
  <strong>No.Factura:</strong>
  <%= @gasto.no_factura %>
</p>
<p>
  <strong>Fecha:</strong>
  <%= @gasto.fecha %>
</p>
<%= link_to 'Edit', edit_gasto_path(@gasto) %> |
<%= link_to 'Back', gastos_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.select :role ,["admin", "user"], include_blank: true %>
   
  </div>

<div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table class="table table-hover table-bordered" border="2"  width="400">
  <thead>
    <tr>
      <th>Email</th>
      <th>Role</th>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user,  :class=>"btn-info btn-sm"  %></td>
        <td><%= link_to 'Edit', edit_user_path(user), :class=>"btn-warning btn-sm"  %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path,  :class=>"btn btn-success" %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>